import pybullet as p
import constants as c
import numpy
import pybullet_data
import time
import pyrosim.pyrosim as pyrosim
import random

from simulation import SIMULATION
import sys

directOrGUI =  sys.argv[1]
simulation = SIMULATION(directOrGUI) # create an object -- an instance of the SIMULATION class -- called simulation.
simulation.Run()
# simulation.Get_Fitness()

# def random_range(min, max):
#     return (max - min) * random.random() + min
#
# BackLeg_targetAngles = numpy.sin(numpy.linspace(0, 2 * numpy.pi, 1000)) # create 1000 values in sin wave
# FrontLeg_targetAngles = numpy.sin(numpy.linspace(0, 2 * numpy.pi, 1000)) # create 1000 values in sin wave
#
# for i in range(1000):
#     BackLeg_targetAngles[i] = c.BackLeg_amplitude * numpy.sin(c.BackLeg_frequency * i + c.BackLeg_phaseOffset)
#     FrontLeg_targetAngles[i] = c.FrontLeg_amplitude * numpy.sin(c.FrontLeg_frequency * i + c.FrontLeg_phaseOffset)
#
# def scale_to_range(arr, min_range, max_range):
#       min_val = numpy.min(arr)
#       max_val = numpy.max(arr)
#       return ((arr - min_val) / (max_val - min_val)) * (max_range - min_range) + min_range
#
# BackLeg_targetAngles = scale_to_range(BackLeg_targetAngles, -numpy.pi/4, numpy.pi/4) # scale to radians
# FrontLeg_targetAngles = scale_to_range(FrontLeg_targetAngles, -numpy.pi/4, numpy.pi/4) # scale to radians
#
# numpy.save('data/BackLeg_targetAngles.npy', BackLeg_targetAngles)
# numpy.save('data/FrontLeg_targetAngles.npy', FrontLeg_targetAngles)
#
# # exit()
# for i in range(1000):
#     print(i)
#     p.stepSimulation()
#
#     # backLegTouch = pyrosim.Get_Touch_Sensor_Value_For_Link("Torso")
#     # print(backLegTouch)
#     # backLegSensorValues[i] = backLegTouch # Now let's store the sensor values generated by the robot in this vector
#
#     backLegSensorValues[i] = pyrosim.Get_Touch_Sensor_Value_For_Link("BackLeg")
#     frontLegSensorValues[i] = pyrosim.Get_Touch_Sensor_Value_For_Link("Torso") # unsure if will work with frontleg
#
#     pyrosim.Set_Motor_For_Joint(
#     bodyIndex = robotId,
#     jointName = b'Torso_BackLeg',
#     controlMode = p.POSITION_CONTROL,
#     targetPosition = BackLeg_targetAngles[i],
#     maxForce = 500)
#
#     pyrosim.Set_Motor_For_Joint(
#     bodyIndex = robotId,
#     jointName = b'Torso_FrontLeg',
#     controlMode = p.POSITION_CONTROL,
#     targetPosition =  FrontLeg_targetAngles[i],
#     maxForce = 500)
#
#     time.sleep(c.SLEEP_CONSTANT)
#
# numpy.save('data/backLegSensorValues.npy', backLegSensorValues)
# numpy.save('data/frontLegSensorValues.npy', frontLegSensorValues)
#
# p.disconnect()
#
