from simulation import SIMULATION
from world import WORLD
from robot import ROBOT

simulation = SIMULATION()

# import pybullet as p
# import constants as c
# import numpy
# import pybullet_data
# import time
# import pyrosim.pyrosim as pyrosim
# import random
#
# physicsClient = p.connect(p.GUI)
# p.setAdditionalSearchPath(pybullet_data.getDataPath())
# p.configureDebugVisualizer(p.COV_ENABLE_GUI,0)
#
# p.setGravity(0,0,-9.8) #responsible for determining what forces exist in our world. The first, most obvious one to add is gravity.
# planeId = p.loadURDF("plane.urdf") # add floor
# robotId = p.loadURDF("body.urdf")
# p.loadSDF("world.sdf") #tells pybullet to read in the world described in box.sdf.
#
# pyrosim.Prepare_To_Simulate(robotId)
#
# def random_range(min, max):
#     return (max - min) * random.random() + min
#
# for i in range(1000):
#     c.BackLeg_targetAngles[i] = c.BackLeg_amplitude * numpy.sin(c.BackLeg_frequency * i + c.BackLeg_phaseOffset)
#     c.FrontLeg_targetAngles[i] = c.FrontLeg_amplitude * numpy.sin(c.FrontLeg_frequency * i + c.FrontLeg_phaseOffset)
#
# def scale_to_range(arr, min_range, max_range):
#       min_val = numpy.min(arr)
#       max_val = numpy.max(arr)
#       return ((arr - min_val) / (max_val - min_val)) * (max_range - min_range) + min_range
#
# BackLeg_targetAngles = scale_to_range(c.BackLeg_targetAngles, -numpy.pi/4, numpy.pi/4) # scale to radians
# FrontLeg_targetAngles = scale_to_range(c.FrontLeg_targetAngles, -numpy.pi/4, numpy.pi/4) # scale to radians
#
# numpy.save('data/BackLeg_targetAngles.npy', BackLeg_targetAngles)
# numpy.save('data/FrontLeg_targetAngles.npy', FrontLeg_targetAngles)
#
# # exit()
# for i in range(1000):
#     print(i)
#     p.stepSimulation()
#
#     # backLegTouch = pyrosim.Get_Touch_Sensor_Value_For_Link("Torso")
#     # print(backLegTouch)
#     # backLegSensorValues[i] = backLegTouch # Now let's store the sensor values generated by the robot in this vector
#
#     c.frontLegSensorValues[i] = pyrosim.Get_Touch_Sensor_Value_For_Link("FrontLeg")
#     c.backLegSensorValues[i] = pyrosim.Get_Touch_Sensor_Value_For_Link("BackLeg") # broken
#
#     pyrosim.Set_Motor_For_Joint(
#     bodyIndex = robotId,
#     jointName = b'Torso_BackLeg',
#     controlMode = p.POSITION_CONTROL,
#     targetPosition = BackLeg_targetAngles[i],
#     maxForce = 500)
#
#     pyrosim.Set_Motor_For_Joint(
#     bodyIndex = robotId,
#     jointName = b'Torso_FrontLeg',
#     controlMode = p.POSITION_CONTROL,
#     targetPosition =  FrontLeg_targetAngles[i],
#     maxForce = 500)
#
#     time.sleep(c.SLEEP_CONSTANT)
#
# numpy.save('data/backLegSensorValues.npy', c.backLegSensorValues)
# numpy.save('data/frontLegSensorValues.npy', c.frontLegSensorValues)
#
# p.disconnect()
#
